Feature/kanban board
gss78/TaskManager pull request #14
Opened 2021-09-08 10:05 UTC by gss78

2021-09-08 17:07 UTC, greybutton requested changes

2021-09-08 17:07 UTC, greybutton commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
поставь плис версию 0.3.2, с бетой проблемы могут быть

2021-09-08 17:07 UTC, greybutton commented on package.json
> +    "@lourenci/react-kanban": "^2.1.0",
обновил плис на @asseinfo/react-kanban

2021-09-08 17:07 UTC, greybutton commented on package.json
> +  },
это для чего?

2021-09-08 17:15 UTC, gss78 commented on package.json
> +  },
здесь рекомендуют 
https://styled-components.com/docs/basics

2021-09-08 17:17 UTC, greybutton commented on package.json
> +  },
хорошо, оставь

2021-09-08 18:08 UTC, gss78 commented on package.json
> +    "@lourenci/react-kanban": "^2.1.0",
done

2021-09-08 18:09 UTC, gss78 commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
поменял

2021-09-10 14:54 UTC, greybutton approved these changes

2021-09-10 15:38 UTC, merged