Feature/tasks
gss78/TaskManager pull request #15
Opened 2021-09-18 12:22 UTC by gss78

2021-09-21 16:27 UTC, greybutton requested changes

2021-09-21 16:27 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
1 почему добавил сортировку по дате?
2 сортировка делается через рансак, в проекте есть RANSACK_DEFAULT_SORT

2021-09-21 16:27 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +    return axios.delete(url, body).then(camelize);
для удаления боди не нужно

2021-09-21 16:27 UTC, greybutton commented on lib/tasks/js_routes.rake
> +    ROUTES_DIR = File.join('routes')
почему не `routes_dir = File.join('app', 'javascript', 'routes')`?

2021-09-21 16:27 UTC, greybutton commented on package.json
> +    "ramda": "^0.27.1",
не хватает пакета qs

2021-09-21 17:43 UTC, gss78 commented on package.json
> +    "ramda": "^0.27.1",
https://github.com/gss78/TaskManager/pull/15/commits/8a512e03b2047f7cd9b673ea2d224ac894c6e37e

2021-09-21 17:47 UTC, gss78 commented on lib/tasks/js_routes.rake
> +    ROUTES_DIR = File.join('routes')
такая ошибка при генерации 

rails js_routes:generate
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /task_manager/app/javascript/app/javascript/routes/ApiRoutes.js
/task_manager/lib/tasks/js_routes.rake:11:in `block (2 levels) in <main>'
/task_manager/bin/rails:4:in `<main>'
Tasks: TOP => js_routes:generate
(See full trace by running task with --trace)

2021-09-21 18:00 UTC, gss78 commented on app/javascript/utils/fetchHelper.js
> +    return axios.delete(url, body).then(camelize);
https://github.com/gss78/TaskManager/pull/15/commits/cc55beb384feecd073df992f621475c057350711

2021-09-21 18:11 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
здесь наверное основной момент не в created_at а в том что у нового таска id максимальный + надо использовать возможности ransack,
правильно как сделать? переопределить ransack_params в Api::V1::TasksController

насчет RANSACK_DEFAULT_SORT, сейчас только заметил он и по 'id ASC' (RANSACK_DEFAULT_SORT = 'id ASC'.freeze в /task_manager/app/controllers/api/v1/application_controller.rb) не сортирует

2021-09-21 19:00 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
> правильно как сделать?
зависит от того, что хочешь получить. Пока не понимаю, какой результат хочешь

2021-09-21 19:03 UTC, greybutton commented on lib/tasks/js_routes.rake
> +    ROUTES_DIR = File.join('routes')
странно, ладно оставим

2021-09-21 19:04 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
поправить сортировку на бэкенде, чтобы новые карточки появлялись вверху колонки.

2021-09-21 19:05 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
над этим работаю

2021-09-21 19:43 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
может попробовать `RANSACK_DEFAULT_SORT = 'id desc'.freeze`

2021-09-21 20:31 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
с дефолтной сортировкой по всякому пробовал не работает (по RANSACK_DEFAULT_SORT, код здесь https://learn.dualboot.ru/courses/5/lessons/79/practices/1190)

сделал так
https://github.com/gss78/TaskManager/pull/15/commits/28758cce5ff3184f782ca561c5381b9af9382191

2021-09-21 20:37 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
p.s. 
в development.log в запросах при этой дефолтной сортировке ORDER BY нет.

2021-09-22 07:59 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
попробуй такой ransack_params, это в любом случае через рансак должно делаться. Через ОРМ не прописываем сортировку, чтобы у фронта оставалась возможность по разному делать сортировки
```
  def ransack_params
    q = params.to_unsafe_h.fetch(:q, { s: RANSACK_DEFAULT_SORT })
    q[:s] = RANSACK_DEFAULT_SORT
    q
  end
```

2021-09-23 07:09 UTC, gss78 commented on app/controllers/api/v1/tasks_controller.rb
> +      order(created_at: :desc)
спасибо. помогло

https://github.com/gss78/TaskManager/pull/15/commits/2c358a6ed4fefe409da6adc8ecc6e16c2fdfbdbc

захардкодить сортировку не очень хорошая идея, согласен.

2021-09-23 18:13 UTC, greybutton approved these changes

2021-09-23 18:20 UTC, merged