Feature/redux
gss78/TaskManager pull request #17
Opened 2021-10-12 16:37 UTC by gss78

2021-10-12 18:59 UTC, greybutton requested changes

2021-10-12 18:59 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +
лучше добавить отдельную функцию loadColumnMore которая будет похожа на loadColumn, но внутри будет объединение загруженного и текущего стейта. Сейчас replaceItems, mergeItems больше вопросов вызывают.  loadColumnMore даст семантики и контекста, да будет дублирование, но здесь лучше дублирование, чем плохая абстракция и параметры-флаги

2021-10-12 18:59 UTC, greybutton commented on app/javascript/App.js
> +  </Provider>
mui theme не стал подключать?

2021-10-13 09:08 UTC, gss78 commented on app/javascript/slices/TasksSlice.js
> +
посмотри plz 
https://github.com/gss78/TaskManager/pull/17/commits/dae6883f3dfbc855048ec7d26d82f48f7c9c0b2e

2021-10-13 09:18 UTC, gss78 commented on app/javascript/App.js
> +  </Provider>
да, не понял что импорт, те откуда это взять

import MUITheme from 'MUITheme/MUITheme';

или имееться ввиду 

import { ThemeProvider } from "@material-ui/styles";

потом определение theme

и 

<ThemeProvider theme={theme}>
...
</ThemeProvider>

добавлю, просто хотелось бы уточнить.

2021-10-14 18:52 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +      cards.items = [...column.cards, ...data.items];
`const cards = { items: [...data.items], meta: { ...data.meta } };`
выглядит как просто копирование, не очень понятно зачем и можно без мутации `cards.items = `

```
data = { items: [...column.cards, ...data.items], meta: data.meta, columnId: state }
loadColumnSuccess(data)
```

вообще лучше добавить в reducers `loadColumnMoreSuccess` и там это все сделать, тогда колонка один раз будет искаться и не нужен будет `const board = useSelector((state) => state.TasksSlice.board);`

то, что loadColumnMoreSuccess будет почти повторять loadColumnSuccess это ок

2021-10-14 18:52 UTC, greybutton commented on app/javascript/App.js
> +  </Provider>
самому создать файл `app/javascript/MUITheme/MUITheme.js` и в нем уже использовать ThemeProvider, createMuiTheme. В верном направлении код написал <ThemeProvider `theme={theme}\>`

2021-10-15 06:20 UTC, gss78 commented on app/javascript/slices/TasksSlice.js
> +      cards.items = [...column.cards, ...data.items];
сложно не согласиться,
https://github.com/gss78/TaskManager/pull/17/commits/9d82f7ed4c29281b62018bf280b2dafa910762c9

2021-10-15 07:44 UTC, gss78 commented on app/javascript/App.js
> +  </Provider>
посмотри plz
https://github.com/gss78/TaskManager/pull/17/commits/fd6a07a98941db0336b6a5d129b5183c3dacb934

2021-10-16 09:10 UTC, greybutton approved these changes

2021-10-17 14:54 UTC, merged