Feature/devops/coveralls
gss78/TaskManager pull request #20
Opened 2021-10-20 10:43 UTC by gss78

2021-10-21 18:28 UTC, greybutton requested changes

2021-10-21 18:28 UTC, greybutton commented on test/test_helper.rb
> +Coveralls.wear!
CI прокинут, но не используется. Его здесь надо использовать, генерировать покрытие тестами только если в CI, сейчас на любой  запуск тестов будет генерировать

2021-10-22 03:03 UTC, gss78 commented on test/test_helper.rb
> +Coveralls.wear!
ok,

https://github.com/gss78/TaskManager/pull/20/commits/f291ebc7da972fedb21ea188f37f6a3cc6f6a9e1

2021-10-22 19:11 UTC, greybutton approved these changes

2021-10-23 14:20 UTC, merged