Feature/mailer
gss78/TaskManager pull request #26
Opened 2021-11-04 10:23 UTC by gss78

2021-11-06 18:22 UTC, Andrew8xx8 requested changes

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +    # Before filters
Комментарии — это плохая практика, стоит писать код, который объясняет сам себя в итоге комментарии будут не нужны.

В данном случае их стоит просто удалить.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user, only: [:edit, :update]
Использовать `before_action` — порочная практика. Это неявный вызов какого-то кода, что усложняет понимание происходящего.

Яркий пример когда это ломается есть даже в этом файле. В перед вызовом `create` произойдет вызов `get_user`, в котором будет установлена переменная `@user`, но сразу же в первой строке экшна `create` эта переменная будет перезаписана. В итоге `get_user` вызывается, но не на что не влияет, возможно так вышло потому этот факт просто ускользнул из внимания, т.к. при чтении метода каждый раз сложно проходиться по всем колбекам по всей иерархии, чтобы восстановить картину происходящего.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user, only: [:edit, :update]
Тоже самое касается и двух других строчек, если нужно вызвать где-то метод, просто стоит его вызвать и все, не нужно это делать через колбек

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +    @user = User.find_by(email: params[:password_reset][:email].downcase)
Здесь нет `permit` параметров, так что это не должно работать. Ниже определён как раз метод `user_params` который и должен быть использован для доступа к параметрам.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +    if params[:user][:password].empty?
Здесь нет permit параметров, так что это не должно работать. Ниже определён как раз метод user_params который и должен быть использован для доступа к параметрам.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user, only: [:edit, :update]
Бывают случаи когда это оправдано, например авторизация делается так, когда действительно для ВСЕХ методов по умолчанию нужно закрыть доступ и при появлении новых это правило должно оставаться в силе. Если такое поведение не нужно и появляются какие-то граничные случаи и списки исключений растут от колбека стоит отказаться.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/models/user.rb
> +  def User.new_token
Если нужны методы уровня класса, стоит использовать структуру вида

```
class << self
  # ваши методы внутри блока
end
```

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/models/user.rb
> +  def User.new_token
В добавок:
1. функциональность генерации токена никак не завязана на пользователя и хорошо бы этот код не добавлять непосредственно в модель User. Стоит вынести в модуль
2. Есть решение еще лучше использовать стандартный механизм `has_secure_token`, что в принципе все упростить и этот код будет не нужен. https://api.rubyonrails.org/classes/ActiveRecord/SecureToken/ClassMethods.html

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/models/user.rb
> +    update_attribute(:reset_digest, User.digest(reset_token))
Зачем обновлять каждый аттрибут отдельно, если есть `update`? В прочем, ниже есть совет после применения которого этот код будет не нужен

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/views/user_mailer/password_reset.html.slim
> += render layout:'layout' do
Здесь точно нужно `layout`? Должно без `render` в шаблоне работать, это надо убрать и разобраться. В принципе лейаут можно назначить и в экшне как параметр `render` или на уровне контроллера.

2021-11-06 18:22 UTC, Andrew8xx8 commented on app/views/user_mailer/task_created.html.slim
> += render 'layout' do
Тут и ниже тоже без render 'layout' должно быть

2021-11-08 11:38 UTC, gss78 commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user, only: [:edit, :update]
насчет before_action ясно, 
может что упустил, а почему перед create будет вызов get_user если only: [:edit, :update]?  

исправления здесь

https://github.com/gss78/TaskManager/pull/26/commits/016e4fba8f5f999aaa0f70e1ca7550571f11053d

2021-11-17 15:30 UTC, gss78 commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user, only: [:edit, :update]
Андрей, будет время посмотри plz.

2021-11-22 12:09 UTC, Andrew8xx8 approved these changes

2021-11-22 12:12 UTC, merged