Feature/models gems
gss78/TaskManager pull request #3
Opened 2021-08-10 18:26 UTC by gss78

2021-08-12 17:04 UTC, greybutton requested changes

2021-08-12 17:04 UTC, greybutton commented on Gemfile
> +group :development, :test do
уже есть такая группа, добавь в нее гемы

2021-08-13 05:54 UTC, gss78 commented on Gemfile
> +group :development, :test do
добавил

2021-08-13 18:38 UTC, greybutton commented on Gemfile
> +group :development, :test do
отправь на сайте снова на проверку

2021-08-13 18:44 UTC, greybutton approved these changes

2021-08-15 08:35 UTC, merged