Feature/models generation
gss78/TaskManager pull request #4
Opened 2021-08-16 10:23 UTC by gss78

2021-08-16 18:49 UTC, greybutton requested changes

2021-08-16 18:49 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :string, aliases: [:state, :description, :name, :first_name, :last_name, :password, :avatar] do |n|
state не будет случайной строкой, можно сейчас убрать

2021-08-16 18:49 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :type, ['Admin', 'Manager', 'Developer'].cycle
почему используется cycle?

2021-08-16 18:49 UTC, greybutton commented on test/factories/sequence.rb
> +    Date.today + rand(10..20)
здесь генерируется datetime?

2021-08-16 19:07 UTC, gss78 commented on test/factories/sequence.rb
> +  sequence :string, aliases: [:state, :description, :name, :first_name, :last_name, :password, :avatar] do |n|
ok, в test/factories/tasks.rb если  state {'new_task'}, нормально?

2021-08-16 20:08 UTC, gss78 commented on test/factories/sequence.rb
> +  sequence :type, ['Admin', 'Manager', 'Developer'].cycle
согласен cycle здесь не нужен,
(в этом варианте он возвращает объект Enumerator, в других nil)
если вариант с генерацией рандомного типа приемлем
как-то так можно ['Admin', 'Manager', 'Developer'].sample
или тут вообще по другому надо?

2021-08-17 06:11 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :string, aliases: [:state, :description, :name, :first_name, :last_name, :password, :avatar] do |n|
да

2021-08-17 06:13 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :type, ['Admin', 'Manager', 'Developer'].cycle
sample подходит, но можно убрать этот sequence, ведь type задаем в factory :user

2021-08-17 06:16 UTC, gss78 commented on test/factories/sequence.rb
> +  sequence :type, ['Admin', 'Manager', 'Developer'].cycle
да что-то загнался я

2021-08-17 18:14 UTC, gss78 commented on test/factories/sequence.rb
> +  sequence :type, ['Admin', 'Manager', 'Developer'].cycle
https://github.com/gss78/TaskManager/pull/4/commits/304465a4843a6377bd68fae907fcbe723c67f42e

2021-08-17 19:08 UTC, greybutton approved these changes

2021-08-18 05:18 UTC, merged